spring.application.name=backend
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fashion?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:codegym}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
server.forward-headers-strategy=native
paypal.client-id=AWjtSghYL5RCjYiYhYcZmogDNg_VcIvt6ZDAFb1rC9rsthgUWYm5hkGNDbbOO6n_Uyb7cAz0I5Ui4Z5s
paypal.secret=ELZoiUh5h9ueA8BV5QNe2UwoszQfVskUq5smyWuxnuR1YS7x3UT0i1JV-Nm4v8ehrsL8zLUh_4fsG6mZ
paypal.mode=sandbox
google.client-id=${GOOGLE_CLIENT_ID}
google.client-secret=${GOOGLE_CLIENT_SECRET}
google.redirect-uri=${GOOGLE_REDIRECT_URI}
brevo.api-key=${BREVO_API_KEY:}




